### ISSUE TITLE
0.14.1 has no feature bound on alloc

### ISSUE THREAD

**Issue by eloc3147** [NULLx76/ringbuffer#119]
Not sure how this happened, but the published 0.14.1 version of this crate has no `#[cfg(feature = "alloc")]` bound on the `extern crate alloc` import. I'm not sure which revision this is as there is no tag or release for 0.14.1.

**Comment by NULLx76** [comment]
Also unsure what happened there, I published version `0.14.2` that fixes this

**Comment by eloc3147** [comment]
Er, sorry. I probably should have checked that the current master branch of this crate compiles without the `alloc` feature enabled.

I made a PR (#120) to get compiling without `alloc` working again and a test to hopefully prevent this in future.
