### ISSUE TITLE
Does ring buffer support mpmc?

### ISSUE THREAD

**Issue by codehobbyist06** [NULLx76/ringbuffer#131]
Hi team,
I wanted to know, if the AllocRingBuffer structure in the ringbuffer crate supports mpmc mode. I want to use the ring concurrently by multiple threads to push and remove objects simultaneously.
Also, if yes what is the underlying synchronization mechanism used by the ring?

**Comment by NULLx76** [comment]
Currently the ringbuffer does not support mpmc, currently the implemented structure does not really allow for it.

**Comment by jdonszelmann** [comment]
Unfortunately it cannot. Such an implementation would be completely different from the inside than the one we have, and this is not a goal we have for ringbuffer. Instead, you likely want to use stds channel or add a lock to the ringbuffer. On embedded systems we have used ringbuffer as a channel, but then interrupts are turned off when writing to them, from for example an interrupt handler.
