### ISSUE TITLE
Unsound API

### ISSUE THREAD

**Issue by Plecra** [NULLx76/ringbuffer#25]
https://github.com/NULLx76/ringbuffer/blob/7adb361f8b0e6fe596dbbdce251e850e84b0510d/src/ringbuffer_trait.rs#L211

This transmute is unsound, since it is implemented on top of the `RingBuffer` trait.

```rust
use ringbuffer::RingBuffer;

struct NaughtyRingBuffer<T>(T);
impl<T: ...> RingBuffer<T> for NaughtyRingBuffer<T> {
    fn get_mut(&mut self, _: isize) -> Option<&mut T> {
        Some(&mut self.0)
    }
    fn len(&self) -> usize {
        2
    }
    // .. other required methods
}

let mut rb = NaughtyRingBuffer(0);
let mut iter = rb.iter();
let first = iter.next().unwrap(); // First `&mut i32`
let second = iter.next(); // Overlapping borrow
```

**Comment by Plecra** [comment]
Oh this isn't allowed either

https://github.com/NULLx76/ringbuffer/blob/9bdcebff04dc808d561b197f4c87a8071b4b6b28/src/with_const_generics.rs#L70

> Moreover, uninitialized memory is special in that the compiler knows that it does not have a fixed value. This makes it undefined behavior to have uninitialized data in a variable even if that variable has an integer type, which otherwise can hold any fixed bit pattern:

i.e. There's no way for a user to call `new_uninit` soundly

**Comment by NULLx76** [comment]
@Plecra are we correct in the assumption that #26 fix these soundness problems?
