### ISSUE TITLE
Why not Apache License?

### ISSUE THREAD

**Issue by gembin** [NULLx76/ringbuffer#57]

**Comment by jonay2000** [comment]
Please explain

**Comment by bcantrill** [comment]
I can't speak for @gembin, but for us, this crate sticks out like a sore thumb:  it is the only of our dependencies (among thousands) that is LGPL. That is itself *okay*, but it means that after every license audit, we are asking ourselves why we are using this. The prevailing license in the Rust crate ecosystem is overwhelmingly MIT/Apache; having this be available under MIT or Apache (or MPLv2 or BSD-3) would allow us to stop asking this question on every scan. Hope that helps!

**Comment by jonay2000** [comment]
I see, what do you think @NULLx76? I think switching to MIT would be fine. To be quite honest I forgot what the original thought process was to do GPL and I actually thought it already was MIT. If @NULLx76 is okay with it, I'm also fine with changing it.

**Comment by jonay2000** [comment]
Just merge #63 if you're okay

**Comment by gembin** [comment]
Exactly as @bcantrill explained.

**Comment by NULLx76** [comment]
> I can't speak for @gembin, but for us, this crate sticks out like a sore thumb:  it is the only of our dependencies (among thousands) that is LGPL. That is itself *okay*, but it means that after every license audit, we are asking ourselves why we are using this. The prevailing license in the Rust crate ecosystem is overwhelmingly MIT/Apache; having this be available under MIT or Apache (or MPLv2 or BSD-3) would allow us to stop asking this question on every scan. Hope that helps!

Yeah this is totally fair, to be honest not much thought went into the initial license. So I'm totally okay changing it to MIT
