### ISSUE TITLE
RingBufferMutIterator doesn't actually impl Iterator

### ISSUE THREAD

**Issue by svenstaro** [NULLx76/ringbuffer#69]
Currently, `RingBufferMutIterator` doesn't actually `impl Iterator` and that's a bit annoying when you want to do something like `for element in buffer.iter_mut() {}`. This was apparently removed in eb7ff21e684bc5309e6f65d8be815df3853d02cc but it's now just really misleading as the name implies that it's an `Iterator` but it's actually not. Can this again be made to `impl Iterator`?

**Comment by NULLx76** [comment]
If I recall correctly implementing Iterator makes our unsafe code unsound, see also #25 and #27.

**Comment by svenstaro** [comment]
Well maybe there's a better way. The current implementation is also not great for the reason I outlined

**Comment by NULLx76** [comment]
We will likely be able to fix this using GATs but those aren't on stable (yet)

**Comment by svenstaro** [comment]
But they soon will be. :)

**Comment by jonay2000** [comment]
The problem is, that GATs alone doesn't solve this. GATs only make the technology possible to even start implementing this. What you need is lending iterators. That's what we've implemented manually here, a lending iterator. Just adding GATs is not enough, the standard library (and built-in for loops) need to support iterating over types that lend out their contents. This is probably going to be stable in rust 2024, if ever.

Sorry :(

**Comment by jonay2000** [comment]
Though I'd also like this to be the case, for the time being this is close to impossible without adding lots of unsafe (and likely fundamentally unsound) code to ringbuffer.

**Comment by jonay2000** [comment]
I recommend you to give it a try, and you'll quickly find that it's impossible. Just try to implement Iterator for RingbufferMutIterator, and try to get the lifetimes right. It won't work because it currently can't work.

**Comment by svenstaro** [comment]
Then I think the `iter_mut()` should be removed completely or renamed. It's rather misleading for users right now and I spend a good 20 minutes looking at my code until I went ahead and check this library's code about the implementation.

I guess the question is: Do you _require_ this library to 100% safe code or would you accept the mut iterator to be implemented in an unsafe fashion?

**Comment by jonay2000** [comment]
We used to have such an unsafe implementation, and it proved to be unsound. I wouldn't want to go back to that. If we can prove, using for example miri, that an unsafe system that does this is sound for both our implementations, and for any implementation a user may give of the ringbuffer traits, then I'm not against it. However, it would take me some time to implement this well, it it's feasible at all. But by all means go ahead and help us if you want! I do also think that the while let loop you need to use the current iter mut version is not that bad, but it may just need better documentation. And that I'm all for. In general I'm not against unsafe code, just look at our const generic ringbuffer, and how it uses maybeuninit to be more efficient.

**Comment by svenstaro** [comment]
I won't have time to work on any of this. I agree that `while let` works well enough but I just don't like how the naming currently implies an `impl Iterator` when it fact that's not the case. Normally you'd expect to go from `.iter()` to `.iter_mut()` and see the same semantics.

**Comment by jonay2000** [comment]
After a morning of research I finally figured out how to implement this with unsafe-but-sound code (checked by miri)
